/**
 * Where things live on disk.
 *
 * Resolved from `import.meta.url` rather than from `process.cwd()`, because
 * npm runs a workspace script with the *package* as the working directory:
 * `npm run db:seed` from the repo root would otherwise write
 * `packages/db/data/shopquote.db`. Everything the app writes belongs under one
 * `data/` directory at the repo root — that directory is what §7's nightly
 * backup copies.
 *
 * This module resolves the same way from `src/` (tests, run through Vitest)
 * and from `dist/` (the built CLIs), because both are one level below the
 * package root.
 */

import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** `packages/db/` — one level above this file, whether it sits in `src` or `dist`. */
export const packageRoot = fileURLToPath(new URL('../', import.meta.url));

/** The repo root: `packages/db/` → `packages/` → here. */
export const repoRoot = join(packageRoot, '..', '..');

/** Generated by `drizzle-kit generate`; read by the migrator at runtime. */
export const migrationsDir = join(packageRoot, 'drizzle');

/** The workbook extract: `scripts/extract-workbook.py` writes here. */
export const seedDir = join(packageRoot, 'seed');

/** Everything the running app owns: the SQLite file and `attachments/` (§7). */
export function dataDir(): string {
  const configured = process.env['SHOPQUOTE_DATA_DIR'];
  return configured !== undefined && configured !== '' ? configured : join(repoRoot, 'data');
}

/**
 * The database file. `SHOPQUOTE_DB_PATH` wins, then `SHOPQUOTE_DATA_DIR`, then
 * `<repo>/data/shopquote.db` — which is what BUILD-PLAN 2.1's acceptance check
 * looks for.
 */
export function defaultDbPath(): string {
  const configured = process.env['SHOPQUOTE_DB_PATH'];
  if (configured !== undefined && configured !== '') return configured;
  return join(dataDir(), 'shopquote.db');
}

/** Create a directory and its parents. Called before opening the database. */
export function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true });
}
