import { describe, expect, it } from 'vitest';

import { CALC_SCHEMA_VERSION } from '../src/index.js';
import golden from './fixtures/golden-workbook.json' with { type: 'json' };

/**
 * Scaffold-level checks only (BUILD-PLAN Task 1.1). The real parity test
 * arrives in Task 1.4 as `golden.test.ts`.
 *
 * The fixture is generated by `scripts/extract-workbook.py`, and until the
 * engine exists nothing else would notice a re-run that produced a truncated
 * or drifted file. So this guards exactly the oracle and nothing else: the six
 * selling prices, the six material percentages, and the five named
 * intermediates. Assertions on any other workbook number do not belong here or
 * anywhere else -- see docs/course-correction.md §1.2.
 */
describe('scaffold', () => {
  it('exports a schema version', () => {
    expect(CALC_SCHEMA_VERSION).toBe(1);
  });
});

describe('golden fixture (REQUIREMENTS §9)', () => {
  it('carries the six quantity breaks', () => {
    expect(golden.quantity_breaks).toEqual([1, 5, 10, 30, 50, 100]);
  });

  it('carries the six expected selling prices, to the cent', () => {
    const expected = [37.8286, 8.7413, 6.3413, 4.7413, 4.4213, 4.1813];
    expect(golden.expected.selling_price).toHaveLength(6);
    golden.expected.selling_price.forEach((price, i) => {
      expect(price).toBeCloseTo(expected[i]!, 2);
    });
  });

  it('carries six material percentages of selling price', () => {
    expect(golden.expected.material_pct_of_selling).toHaveLength(6);
    golden.expected.material_pct_of_selling.forEach((pct) => {
      expect(pct).toBeGreaterThan(0);
      expect(pct).toBeLessThan(1);
    });
  });

  it('carries the five named intermediates', () => {
    const { intermediates: i } = golden;
    expect(i.blank_cost).toBeCloseTo(68.8358, 3);
    expect(i.min_charge).toBeCloseTo(8.6045, 3);
    expect(i.material_per_part).toBeCloseTo(2.0859, 3);
    expect(i.material_at_qty_1).toBeCloseTo(10.3254, 3);
    // The workbook reads 0.52255 hours per 100; the engine works per part.
    expect(i.laser_hours_per_part * 100).toBeCloseTo(0.52255, 4);
  });
});
