import { describe, expect, it } from 'vitest';

import { CALC_SCHEMA_VERSION } from '../src/index.js';
import golden from './fixtures/golden-workbook.json' with { type: 'json' };

/**
 * Scaffold-level checks only (BUILD-PLAN Task 1.1). The real parity test
 * arrives in Task 1.4 as `golden.test.ts`.
 *
 * What this does earn its place for: the fixture is generated by
 * `scripts/extract-workbook.py` from the workbook, and nothing else would
 * notice if a re-run produced a malformed or truncated file before the engine
 * exists to price it.
 */
describe('scaffold', () => {
  it('exports a schema version', () => {
    expect(CALC_SCHEMA_VERSION).toBe(1);
  });
});

describe('golden fixture (REQUIREMENTS §9)', () => {
  it('carries the six quantity breaks', () => {
    expect(golden.quantity_breaks).toEqual([1, 5, 10, 30, 50, 100]);
  });

  it('carries the six expected selling prices, to the cent', () => {
    const expected = [37.8286, 8.7413, 6.3413, 4.7413, 4.4213, 4.1813];
    expect(golden.expected.selling_price).toHaveLength(6);
    golden.expected.selling_price.forEach((price, i) => {
      expect(price).toBeCloseTo(expected[i]!, 2);
    });
  });

  it('prices the G30 16 GA part the workbook was saved on', () => {
    expect(golden.material.name).toBe('G30 16 GA (.0598)');
    expect(golden.material.lb_per_sq_ft).toBe(2.656);
    expect(golden.material.speed_in_min).toBe(220);
    expect(golden.nesting.parts_per_blank).toBe(33);
  });
});
